kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: test102
  namespace: testkube
spec:
  content:
    git:
      uri: https://github.com/cerebro1/selenium-testkube.git
      paths:
      - selenium-java
  container:
    workingDir: /data/repo/selenium-java
    image: maven:3.9.6-eclipse-temurin-22-alpine
  services:
    chrome:
      image: selenium/standalone-chrome:4.21.0-20240517
      readinessProbe:
        httpGet:
          path: /wd/hub/status
          port: 4444
        periodSeconds: 1
    edge:
      image: selenium/standalone-edge:4.21.0-20240517
      readinessProbe:
        httpGet:
          path: /wd/hub/status
          port: 4444
        periodSeconds: 1
    firefox:
      image: selenium/standalone-firefox:4.21.0-20240517
      readinessProbe:
        httpGet:
          path: /wd/hub/status
          port: 4444
        periodSeconds: 1
  steps:
  - name: Run Chrome Test
    run:
      env:
      - name: SELENIUM_BROWSER
        value: chrome
      - name: SELENIUM_HOST
        value: '{{ services.chrome.0.ip }}:4444'
      shell: |
        mvn test
        mvn surefire-report:report
        mkdir -p /data/repo/selenium-java/target/chrome-artifacts
        mv /data/repo/selenium-java/target/surefire-reports /data/repo/selenium-java/target/chrome-artifacts/surefire-reports
        mv /data/repo/selenium-java/target/site /data/repo/selenium-java/target/chrome-artifacts/site
    artifacts:
      paths:
      - target/chrome-artifacts/**/*
  - name: Run Edge Test
    run:
      env:
      - name: SELENIUM_BROWSER
        value: edge
      - name: SELENIUM_HOST
        value: '{{ services.edge.0.ip }}:4444'
      shell: |
        mvn test
        mvn surefire-report:report
        mkdir -p /data/repo/selenium-java/target/edge-artifacts
        mv /data/repo/selenium-java/target/surefire-reports /data/repo/selenium-java/target/edge-artifacts/surefire-reports
        mv /data/repo/selenium-java/target/site /data/repo/selenium-java/target/edge-artifacts/site
    artifacts:
      paths:
      - target/edge-artifacts/**/*
  - name: Run Firefox Test
    run:
      env:
      - name: SELENIUM_BROWSER
        value: firefox
      - name: SELENIUM_HOST
        value: '{{ services.firefox.0.ip }}:4444'
      shell: |
        mvn test
        mvn surefire-report:report
        mkdir -p /data/repo/selenium-java/target/firefox-artifacts
        mv /data/repo/selenium-java/target/surefire-reports /data/repo/selenium-java/target/firefox-artifacts/surefire-reports
        mv /data/repo/selenium-java/target/site /data/repo/selenium-java/target/firefox-artifacts/site
    artifacts:
      paths:
      - target/firefox-artifacts/**/*
